spring:
  datasource:
    password: 12345
    username: root 
    url: jdbc:mysql://localhost:3306/fornecedor?useTimezone=true&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
